@startuml


title 電文関連のクラス図

package Model {

    class WritePacket
    {
        - _packetMessage : byte[]
        --
        + Length : byte
        + OpeCode : byte
        ==
        + ToByteArray()        
    }


    class ReadPacket
    {
        - _packetMessage : byte[]
        + {static} FromCommandType(ICommandType)
        + ToByteArray()
    }


}


package Controller {
    class WritePacketController
    {
        - ScannerIoController
        + WritePacketController(WritePacket)
        + CretaeChecksum() : byte[]
    }

    class ReadPacketController
    {
        - ScannerIoController
        + ReadPacketController(ReadPacket)
        + CretaeChecksum() : byte[]
        + IsValidateChecksum() : bool
    }

    class ScannerIoController
    {
        + ReadByte() : byte
        + WriteByte() : bool
    }

    class ScannerIoControllerFactory
    {
        + CreateAndOpen(string) : ScannerIoController
    }
}

WritePacket -down-> WritePacketController : Uses >

ReadPacket -down-> ReadPacketController : Uses >

ScannerIoControllerFactory -up-> ScannerIoController : create >

ScannerIoController -up-* WritePacketController : Has >

ScannerIoController -up-* ReadPacketController : Has >

@enduml

@startuml

package Controller {

    class CommandMessageCollectionController
    {
        + Create(DataItem) : CoomandMessageCollection
    }
}


package Model {

    class CommandMessageCollection
    {
        + {field} Items
    }
}

CommandMessageCollectionController -up-> CommandMessageCollection : Create >


@enduml